import os

iteration = 500000

run_names = [
    # 'CityScapes/faster/x1/original',
    # 'CityScapes/faster/x1/unet',
    # 'CityScapes/faster/x2/unet',
    # 'CityScapes/faster/x2/unet_wo_mask',
    # 'CityScapes/faster/x2/unet_wo_sr',
    # 'CityScapes/faster/x4/unet',
    # 'CityScapes/faster/x4/unet_wo_mask',
    # 'CityScapes/faster/x4/unet_wo_sr',

    # 'CityScapes/fcos/x1/original',
    # 'CityScapes/fcos/x1/unet',
    # 'CityScapes/fcos/x2/unet',
    # 'CityScapes/fcos/x2/unet_wo_mask',
    # 'CityScapes/fcos/x2/unet_wo_sr',
    # 'CityScapes/fcos/x4/unet',
    # 'CityScapes/fcos/x4/unet_wo_mask',
    # 'CityScapes/fcos/x4/unet_wo_sr',

    # 'CityScapes/retinanet/x1/original',
    # 'CityScapes/retinanet/x1/unet',
    # 'CityScapes/retinanet/x2/unet',
    # 'CityScapes/retinanet/x2/unet_wo_mask',
    # 'CityScapes/retinanet/x2/unet_wo_sr',
    # 'CityScapes/retinanet/x4/unet',
    # 'CityScapes/retinanet/x4/unet_wo_mask',
    # 'CityScapes/retinanet/x4/unet_wo_sr',

    # 'CityScapes/ssd/x1/original',
    # 'CityScapes/ssd/x1/unet',
    # 'CityScapes/ssd/x2/unet',
    # 'CityScapes/ssd/x2/unet_wo_mask',
    # 'CityScapes/ssd/x2/unet_wo_sr',
    # 'CityScapes/ssd/x4/unet',
    # 'CityScapes/ssd/x4/unet_wo_mask',
    # 'CityScapes/ssd/x4/unet_wo_sr',

    # 'CityScapes/ssd/x1/unet_wo_ce',
    # 'CityScapes/ssd/x1/unet_wo_pe',
    # 'CityScapes/ssd/x1/unet_wo_pe_ce',
    # 'CityScapes/ssd/x1/unet_wo_pretrain',
    # 'CityScapes/ssd/x1/unet_wo_pretrain_wo_loss',
    # 'CityScapes/ssd/x1/unet_wo_loss',
    # 'CityScapes/ssd/x1/flat',
    # 'CityScapes/ssd/x1/flat_wo_ce',
    # 'CityScapes/ssd/x1/flat_wo_pe',
    # 'CityScapes/ssd/x1/flat_wo_pe_ce',

    # 'CityScapes/ssd/x2/unet_wo_ce',
    # 'CityScapes/ssd/x2/unet_wo_pe',
    # 'CityScapes/ssd/x2/unet_wo_pe_ce',
    # 'CityScapes/ssd/x2/unet_wo_pretrain',
    # 'CityScapes/ssd/x2/unet_wo_pretrain_wo_loss',
    # 'CityScapes/ssd/x2/unet_wo_loss',
    # 'CityScapes/ssd/x2/flat',
    # 'CityScapes/ssd/x2/flat_wo_ce',
    # 'CityScapes/ssd/x2/flat_wo_pe',
    # 'CityScapes/ssd/x2/flat_wo_pe_ce',

    # 'CityScapes/ssd/x4/unet_wo_ce',
    # 'CityScapes/ssd/x4/unet_wo_pe',
    # 'CityScapes/ssd/x4/unet_wo_pe_ce',
    # 'CityScapes/ssd/x4/unet_wo_pretrain',
    # 'CityScapes/ssd/x4/unet_wo_pretrain_wo_loss',
    # 'CityScapes/ssd/x4/unet_wo_loss',
    # 'CityScapes/ssd/x4/flat',
    # 'CityScapes/ssd/x4/flat_wo_ce',
    # 'CityScapes/ssd/x4/flat_wo_pe',
    # 'CityScapes/ssd/x4/flat_wo_pe_ce',

    # 'CityScapes/centernet/x1/original',
    # 'CityScapes/centernet/x1/unet',
    # 'CityScapes/centernet/x2/unet',
    # 'CityScapes/centernet/x2/unet_wo_mask',
    # 'CityScapes/centernet/x2/unet_wo_sr',
    # 'CityScapes/centernet/x4/unet',
    # 'CityScapes/centernet/x4/unet_wo_mask',
    # 'CityScapes/centernet/x4/unet_wo_sr',

    # 'CityScapes/centernet_wo_dcn/x1/original',
    # 'CityScapes/centernet_wo_dcn/x1/unet',
    # 'CityScapes/centernet_wo_dcn/x2/unet',
    # 'CityScapes/centernet_wo_dcn/x2/unet_wo_mask',
    # 'CityScapes/centernet_wo_dcn/x2/unet_wo_sr',
    # 'CityScapes/centernet_wo_dcn/x4/unet',
    # 'CityScapes/centernet_wo_dcn/x4/unet_wo_mask',
    # 'CityScapes/centernet_wo_dcn/x4/unet_wo_sr',

    # 'CityScapes/ssd/x1/unet_mul',
    # 'CityScapes/ssd/x2/unet_mul',
    # 'CityScapes/ssd/x4/unet_mul',

    # 'bdd100k/faster/x1/original',
    # 'bdd100k/faster/x1/unet',
    # 'bdd100k/faster/x2/unet',
    # 'bdd100k/faster/x2/unet_wo_mask',
    # 'bdd100k/faster/x2/unet_wo_sr',
    # 'bdd100k/faster/x4/unet',
    # 'bdd100k/faster/x4/unet_wo_mask',
    # 'bdd100k/faster/x4/unet_wo_sr',

    # 'bdd100k/fcos/x1/original',
    # 'bdd100k/fcos/x1/unet',
    # 'bdd100k/fcos/x2/unet',
    # 'bdd100k/fcos/x2/unet_wo_mask',
    # 'bdd100k/fcos/x2/unet_wo_sr',
    # 'bdd100k/fcos/x4/unet',
    # 'bdd100k/fcos/x4/unet_wo_mask',
    # 'bdd100k/fcos/x4/unet_wo_sr',

    # 'bdd100k/retinanet/x1/original',
    # 'bdd100k/retinanet/x1/unet',
    # 'bdd100k/retinanet/x2/unet',
    # 'bdd100k/retinanet/x2/unet_wo_mask',
    # 'bdd100k/retinanet/x2/unet_wo_sr',
    # 'bdd100k/retinanet/x4/unet',
    # 'bdd100k/retinanet/x4/unet_wo_mask',
    # 'bdd100k/retinanet/x4/unet_wo_sr',

    # 'bdd100k/ssd/x1/original',
    # 'bdd100k/ssd/x1/unet',
    # 'bdd100k/ssd/x2/unet',
    # 'bdd100k/ssd/x2/unet_wo_mask',
    # 'bdd100k/ssd/x2/unet_wo_sr',
    # 'bdd100k/ssd/x4/unet',
    # 'bdd100k/ssd/x4/unet_wo_mask',
    # 'bdd100k/ssd/x4/unet_wo_sr',

    # 'bdd100k/centernet/x1/original',
    # 'bdd100k/centernet/x1/unet',
    # 'bdd100k/centernet/x2/unet',
    # 'bdd100k/centernet/x2/unet_wo_mask',
    # 'bdd100k/centernet/x2/unet_wo_sr',
    # 'bdd100k/centernet/x4/unet',
    # 'bdd100k/centernet/x4/unet_wo_mask',
    # 'bdd100k/centernet/x4/unet_wo_sr',

    # 'CityScapes/ssd/x2/none_bilinear',
    # 'CityScapes/ssd/x2/none_bicubic',
    # 'CityScapes/ssd/x4/none_bilinear',
    # 'CityScapes/ssd/x4/none_bicubic',
    # 'CityScapes/ssd/x2/unet_bicubic',
    # 'CityScapes/ssd/x2/unet_bilinear',
    # 'CityScapes/ssd/x4/unet_bicubic',
    # 'CityScapes/ssd/x4/unet_bilinear',
]

for run in run_names:
    if 'x1' in run:
        os.system(f'python test.py --config_file output/{run}/config.yaml --trained_model output/{run}/model/iteration_{iteration}.pth --output_dirname output/{run}')
    else:
        os.system(f'python test.py --config_file output/{run}/config.yaml --trained_model output/{run}/model/iteration_{iteration}.pth --output_dirname output/{run} --split_forward')
