SOLVER:
  BATCH_SIZE: 6
MODEL:
  DETECTOR:
    CONFIG_FILE: 'model/modeling/detector_configs/centernet.py'
    PRETRAINED_MODEL: 'weights/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth'
  SR:
    FLAG: False
    FACTOR: 1
  MASK:
    FLAG: True
    PRETRAINED_MODEL: 'weights/mask_x1.pth'
