SOLVER:
  BATCH_SIZE: 6
  BOX_THRESHOLD: 0.9
MODEL:
  DETECTOR:
    CONFIG_FILE: 'model/modeling/detector_configs/centernet.py'
    PRETRAINED_MODEL: 'weights/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth'
  SR:
    FLAG: False
    FACTOR: 4
    PRETRAINED_MODEL: 'weights/dbpn_stage4_x4.pth'
  MASK:
    FLAG: True
    PRETRAINED_MODEL: 'weights/mask_x4.pth'
DATA:
  TRAIN:
    IMAGE_DIR: 'datasets/bdd100k/images/100k/train'
    ANN_FILE: 'datasets/bdd100k/labels/det_20_coco/det_train.json'
    MASK_DIR: 'datasets/bdd100k/mask_gts'
  TEST:
    IMAGE_DIR: 'datasets/bdd100k/images/100k/val'
    ANN_FILE: 'datasets/bdd100k/labels/det_20_coco/det_val.json'
    MASK_DIR: 'datasets/bdd100k/mask_gts'