SOLVER:
  BATCH_SIZE: 6
MODEL:
  DETECTOR:
    CONFIG_FILE: 'model/modeling/detector_configs/fcos.py'
    PRETRAINED_MODEL: 'weights/fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth'
  SR:
    FLAG: False
    FACTOR: 1
  MASK:
    FLAG: True
    PRETRAINED_MODEL: 'weights/mask_x1.pth'
