from yacs.config import CfgNode as CN

_C = CN()

_C.SOLVER = CN()
_C.SOLVER.LR = 1e-4
_C.SOLVER.BATCH_SIZE = 8
_C.SOLVER.MAX_ITER = 500000
_C.SOLVER.LR_DECAY = [300000, 450000]
_C.SOLVER.SYNC_BATCHNORM = True



_C.MODEL = CN()
_C.MODEL.ACTIVATION = 'relu'
_C.MODEL.NORMALIZATION = 'batch'
_C.MODEL.BIAS = False

_C.MODEL.SR = CN()
_C.MODEL.SR.ARCITECTURE = 'DDBPN'
_C.MODEL.SR.FACTOR = 1
_C.MODEL.SR.FEAT = 64
_C.MODEL.SR.PRETRAINED_MODEL = ''
_C.MODEL.SR.WEIGHT_FIX = False

_C.MODEL.MASK = CN()
_C.MODEL.MASK.ARCITECTURE = 'UNet'
_C.MODEL.MASK.FEAT = 64
_C.MODEL.MASK.WEIGHT_FIX = False

_C.MODEL.MASK.CONTEXT = CN()
_C.MODEL.MASK.CONTEXT.FLAG = True
_C.MODEL.MASK.CONTEXT.NUM_SCALES = 4
_C.MODEL.MASK.CONTEXT.NUM_CONVS = 3
_C.MODEL.MASK.CONTEXT.NUM_FCS = 3

_C.MODEL.MASK.COOD = CN()
_C.MODEL.MASK.COOD.FLAG = True
_C.MODEL.MASK.COOD.NUM_LAYERS = 1


_C.MODEL.DETECTOR = CN()
_C.MODEL.DETECTOR.CONFIG_FILE = 'model/modeling/detector_configs/ssd512.py'
_C.MODEL.DETECTOR.WEIGHT_FIX = False



_C.DATA = CN()

_C.OUTPUT_DIR = ''
_C.SEED = 123