SOLVER:
  BATCH_SIZE: 6
  BOX_THRESHOLD: 0.9
  MAX_ITER: 100000
  LR_DECAY: [60000, 90000]
MODEL:
  DETECTOR:
    CONFIG_FILE: 'model/modeling/detector_configs/ssd512.py'
    PRETRAINED_MODEL: 'weights/ssd512_coco_20210803_022849-0a47a1ca.pth'
  SR:
    FLAG: False
    FACTOR: 2
    INTERP_METHOD: 'bilinear'
  MASK:
    FLAG: True
    PRETRAINED_MODEL: 'weights/mask_x4.pth'
SEED: 998