SOLVER:
  BATCH_SIZE: 6
  BOX_THRESHOLD: 0.9
MODEL:
  DETECTOR:
    CONFIG_FILE: 'model/modeling/detector_configs/centernet.py'
    PRETRAINED_MODEL: 'weights/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth'
  SR:
    FLAG: True
    FACTOR: 4
    PRETRAINED_MODEL: 'weights/dbpn_stage4_x4.pth'
  MASK:
    FLAG: True
    PRETRAINED_MODEL: 'weights/mask_x4.pth'